version: '3.1'
services:
  web_app:
    build: .
    links:
      - mongo
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: "development"
      APP_ID: "my-app-id"
      MASTER_KEY: "my-master-key"
      DATABASE_URI: "mongodb://mongo:27017/dev"
  mongo:
    image: mongo
    restart: always
    ports:
    - "27017:27017"
    volumes:
      - mongodata:/data/db
  dashboard:
    image: parseplatform/parse-dashboard
    ports:
      - 4040:4040
    environment:
      - PARSE_DASHBOARD_SERVER_URL=http://localhost:1337/parse
      - PARSE_DASHBOARD_APP_ID=my-app-id
      - PARSE_DASHBOARD_MASTER_KEY=my-master-key
      - PARSE_DASHBOARD_APP_NAME=MyApp
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
      - PARSE_DASHBOARD_USER_ID=admin
      - PARSE_DASHBOARD_USER_PASSWORD=admin
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
volumes:
  mongodata: